### ISSUE TITLE
Does it work with assetPrefix?

### ISSUE THREAD

**Issue by jaredsilver** [escaladesports/gatsby-plugin-prefetch-google-fonts#22]
I don't think it does.

**Comment by kitos** [comment]
Here is commit introduced this problem - [fixed slashes for windows inc. relative urls](https://github.com/escaladesports/gatsby-plugin-prefetch-google-fonts/commit/9a4e77fde3c36686ece6bc2aa75f24c262ea9c52#diff-f7b178d5f1eec87a8fd0e537a7c6b811R48)
