### ISSUE TITLE
Question about default options

### ISSUE THREAD

**Issue by stephanschubert** [escaladesports/gatsby-plugin-prefetch-google-fonts#5]
Thank you for this nice plugin!

One question: Why do you change [the default settings) for `minify` and `encode`](https://github.com/SirPole/google-fonts-plugin)?

**Comment by kennedyrose** [comment]
I can't remember if there was a specific reason or not. More than likely, it's just some leftover code from development. Feel free to submit a PR if you'd prefer the plugin's default settings! Thank you!
